### ISSUE TITLE
看不懂

### ISSUE THREAD

**Issue by Notelzg** [zyearn/zaver#12]
在 zaver.c 的 58line 的 while循环中 case ': '  ,这个看不懂， 
    while ((opt=getopt_long(argc, argv,"Vc:?h",long_options,&options_index)) != EOF) {
        switch (opt) {
            case  0 : break;
            case 'c':
                conf_file = optarg;
                break;
            case 'V':
                printf(PROGRAM_VERSION"\n");
                return 0;
            case ':':
            case 'h':
            case '?':
                usage();
                return 0;
        }
    }

man getopt-long  上说，c: 代表 c需要一个参数，
博主你怎么看

**Comment by caisan** [comment]
@Notelzg 是的,"c:"表示的是c后面需要参数,
