### ISSUE TITLE
threadpool.c 中初始化问题

### ISSUE THREAD

**Issue by hardfist** [zyearn/zaver#2]
threadpool.c中，41-45行中，为什么条件变量初始化失败后，要先对lock加锁后再destroy,根据“http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_mutex_destroy.html”，
加锁后未释放锁是未定义行为。

**Comment by zyearn** [comment]
非常感谢你看得那么仔细。你是对的，这里的确写得有问题，不应该加锁的。另外zaver应该还存在或多或少的bug，有兴趣的话可以一起找找
