### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [zyearn/zaver#6]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/zyearn/zaver/blob/414abb7a656125b18a9f33a76725a8d02f2c9f94/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by zyearn** [comment]
@elfring good advice! I will do it latter.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.5/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?
