### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zyearn/zaver#7]
I would like to point out that identifiers like "[`__list_add`](https://github.com/zyearn/zaver/blob/8234ce80e53d75c8bd325537eb48d4e2a541550e/src/list.h#L24)" and "[`_THREADPOOL_H`](https://github.com/zyearn/zaver/blob/414abb7a656125b18a9f33a76725a8d02f2c9f94/src/threadpool.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by zyearn** [comment]
@elfring I learn this kind of usage from [linux source code] (https://github.com/torvalds/linux/blob/master/include/linux/list.h), so for clarity it's better to remain the same

**Comment by technion** [comment]
It's a pattern I've seen in many successful applications, and I've never heard of it being an issue anywhere. Based on account history.. is this just some bot scanning for these names and opening such issues?

**Comment by elfring** [comment]
I dare to repeat some bug reports for various software.

How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by zyearn** [comment]
@elfring Thks. I checked the standard again and you're right. I have refined my code to comply with the standard.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/zyearn/zaver/commit/4a08947da8e3b60eeabbb70cfa85ed80cbb325d4 "Deletion of a few underscores").
How do you think about to make [them](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") not only standard-compliant but also really unique by appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by zyearn** [comment]
maybe #pragma once is better idea? http://stackoverflow.com/questions/1143936/pragma-once-vs-include-guards

**Comment by elfring** [comment]
No if you [care for standard compliance](https://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/ "Is #pragma once part of the C++11 standard?").
