### ISSUE TITLE
你考虑过TCP分片了吗

### ISSUE THREAD

**Issue by wrestle** [zyearn/zaver#9]
假设对方请求数据过大，或你的可接受MTU单元过小，数据被分片发送，恰好只到了一部分数据，你读取了，你的程序似乎不能正确处理。而且这很常见

**Comment by zyearn** [comment]
@wrestle 你说得对，现暂时只能处理小文件情况。实际上现在发送的方式效率很低，要先从内核拷到用户空间，再从用户空间拷到内核发出去，我之后会用sendfile+EPOLLOUT事件来处理发送动作。Thks

**Comment by GuangshanWen** [comment]
求问,这个问题可以通过content-length解决吗?

**Comment by wrestle** [comment]
@GuangshanWen 自然是不能的。Content-Length 属性表示的是 HTTP 报文中的内容段，IPv4中MTU最小是46，这部分是必须的，也就是说不管你发送什么东西给那边，你的包最起码大于46，而既然你发了HTTP包，也就必然大于46(总大小 = 必要部分 + HTTP报文)

**Comment by GuangshanWen** [comment]
@wrestle 多谢童鞋的回复，你上面说的请求数据过大会造成问题，意思是比如request中某个域中参数很大的情况么？

**Comment by GuangshanWen** [comment]
因为我想如果不是单个请求参数过长的话，zaver好像还是可以处理的吧？

**Comment by wrestle** [comment]
@GuangshanWen 最简单的例子，只需要HTTP报文大于(1500-46)字节不管网络环境多好都必定会被分片，这个随便搞一个图片就能复现。因为你没办法控制TCP握手时双方协商的MTU，所以你所说的参数过长与否是你本身无法控制的，如果协商的MTU是50(网络奇差)，那即使你的参数是空，那这次请求的包也会被分片

**Comment by GuangshanWen** [comment]
@wrestle 我主要是觉得在zaver里面只要缓冲区能完全放下请求数据，那分不分片问题不大吧？
